### ISSUE TITLE
conv.c mentioned in data/download_SNAP.sh is missing

### ISSUE THREAD

**Issue by xuyifangreeneyes** [hgyhungry/ge-spmm#1]
Hello, I am running your code for benchmarking. I found `conv.c` mentioned in `data/download_SNAP.sh` is missing in this repo. Can you put it in the repo or explain what it is for? Thanks a lot!

**Comment by hgyhungry** [comment]
Hi @xuyifangreeneyes I just uploaded, thanks for reminding. 

This helper c code and the download bash code are all from http://gitlab.hpcrl.cse.ohio-state.edu/chong/ppopp19_ae , we re-use their interface for sparse matrix loading. Basically this what 'conv.c' does is, it reads the .mtx file from SuiteSparse dataset, removes some comments at the head of the file, adds a short flag indicating the matrix type (symmetric or not, float or int, etc), and the main code recognizes it. No changes to the matrix, just file loading helper. Hope this answers.

**Comment by xuyifangreeneyes** [comment]
Thank you for solving the problem. Sorry I reply late...
