### ISSUE TITLE
How can one pass the aggregation/combiner operators to GE-SPMM

### ISSUE THREAD

**Issue by aydinbuluc** [hgyhungry/ge-spmm#4]
If I wanted to run SpMM with a different aggregation/combiner operator, how can I do that? That seems to be the whole point of the paper but I can't see how the code enables that to the end user.

**Comment by hgyhungry** [comment]
Hello. Changing the aggregator involves changing source code (cuda kernel). We implement it as an SPMM kernel (no need to modify) calling an inline reduction function (which can be replaced), like [here](https://github.com/hgyhungry/ge-spmm/blob/cc9894e9bff39c401800d257d4d0e535d64a63a1/dgl-custom/binary_reduce_max.cu#L18) we do for Graphsage-maxpool. DGL uses [a similar approach](https://github.com/dmlc/dgl/blob/master/src/kernel/cuda/functor.cuh).

**Comment by aydinbuluc** [comment]
Thank you!

Cheers,
- Aydin

**Comment by BenBrock** [comment]
What would be the process for properly calling GE-SPMM?  Copy the code from `topoCacheCoarsenSPMMMaxKernel` and replace `max_init` and `max_reduce` with the desired semiring?

All the SpMM kernels in that file seem to be structure only (no A_values array).  Is there another place I should look for that?  Also, what parameters should I use to invoke the kernel (number of blocks, block size, size of shared memory)?

**Comment by hgyhungry** [comment]
> What would be the process for properly calling GE-SPMM? Copy the code from `topoCacheCoarsenSPMMMaxKernel` and replace `max_init` and `max_reduce` with the desired semiring?
> 
> All the SpMM kernels in that file seem to be structure only (no A_values array). Is there another place I should look for that? Also, what parameters should I use to invoke the kernel (number of blocks, block size, size of shared memory)?

To use ge-spmm I suggest using the c++ function ``spmmWrapper`` in ge-spmm/spmm_test.cu (take argument method=2). All kernels are in the same file for you to track. It has A_values argument. The launch parameters (grid dim, block dim) are calculated in the c++ function from parameters (i.e. B_ncols, A_nrows). 

If you want PyTorch integration, the source code you need are in ge-spmm/pytorch-custom/spmm_kernel.cu, with two top-level functions ``cuda_spmm_no_edge_value`` and ``cuda_spmm``. 

The code in dgl-custom is dedicated for dgl's interface, and may be outdated due to DGL upgrading.

**Comment by BenBrock** [comment]
Thanks for your quick response.  What orientation is expected for B and C?  Looks like row-major?

Also, if I wanted to support a different leading dimension (LD), can you point out which `spmm_test2` I'd need to modify?  It looks like I could modify that by changing the offset calculation on lines 76, 85, 101, and 113, but I'm curious if there's more that would need to be modified.

**Comment by hgyhungry** [comment]
> Thanks for your quick response. What orientation is expected for B and C? Looks like row-major?
> 
> Also, if I wanted to support a different leading dimension (LD), can you point out which `spmm_test2` I'd need to modify? It looks like I could modify that by changing the offset calculation on lines 76, 85, 101, and 113, but I'm curious if there's more that would need to be modified.

The kernels provided in this repo are designed for row-major B and C. I expect they are not performant under column-major settings, in which case I think cusparse is more competitive. Still, if you want to test, you can modify the code related to index calculation to make it work. If you are using spmm_test2 in ge-spmm/spmm_test.cu, for matrix B, line 188, 194-197, 210, 217-223 should include everything you care, and for matrix C refer to line 201-203, 227-233.

**Comment by BenBrock** [comment]
Thanks for the information.  How should I be setting the `tile_row` parameter?  I set it to 4, which appears to be one of the values used in `spmm_test.cu`.

I seem to be getting incorrect results for dense matrices wider than 32 columns.  Could this be related to the `tile_row` parameter, or do you have any recommendation about what I should look into?

**Comment by hgyhungry** [comment]
> Thanks for the information. How should I be setting the `tile_row` parameter? I set it to 4, which appears to be one of the values used in `spmm_test.cu`.
> 
> I seem to be getting incorrect results for dense matrices wider than 32 columns. Could this be related to the `tile_row` parameter, or do you have any recommendation about what I should look into?

''tile_row'' is equal to the number of warps in a thread block, so 4 means 128 threads/block, which is reasonable and should not cause incorrect result. I recommend you to set some tolerance for numerical errors, initialize the output to all-0, and print the row/col number of the wrong results to help identify problems. 

Cheers.

**Comment by hgyhungry** [comment]
closing this
